### ISSUE TITLE
BN do not work when run forward_eval?

### ISSUE THREAD

**Issue by ghoshaw** [yuanyuanli85/tf-hrnet#12]
Hi, I used TF1.11 and run this hrnetw30 in segmentation task. The training process seems ok,  but when it comes to test, if I run  hrnet.forward_eval() , the result is wrong, and if I run  hrnet.forward_train(), the result seems to be right.   
So I got confused. 
The params of BN is used as default,  and I add  "with tf.control_dependencies(tf.get_collection(tf.GraphKeys.UPDATE_OPS)):" before the Optimizer
Do you have any idea for this problem?

**Comment by yuanyuanli85** [comment]
I did not meet such problem.  Have you check the val data feed into forward_train()?  Make sure the valdataset generates similar things as traindataset.

**Comment by ghoshaw** [comment]
Thanks, I will check it out.
