### ISSUE TITLE
请教个模型转换后问题

### ISSUE THREAD

**Issue by alexliyang** [yuanyuanli85/tf-hrnet#16]
请教下， 这里训练好了后转pb模型后，预测试正确的，但是转为tflite模型后推理出错，即推理得到的结果是某个分类总是1.0，请问遇到过吗？有什么办法解决

**Comment by yuanyuanli85** [comment]
我没有试过tflite，你这边是否使用了int8 quantization在转换的时候？ 别的项目里边，我遇到过类似的问题，一般是input的一些preprocess不一样导致的

**Comment by alexliyang** [comment]
@yuanyuanli85   找到转换的问题了，主要是batch_norm的fused那个参数，似乎在tflite中不支持。

有计划出lite hrnet吗？

**Comment by yuanyuanli85** [comment]
目前没有计划去实现 lite hrnet
