### ISSUE TITLE
想直接demo几个算法，对比一下性能？

### ISSUE THREAD

**Issue by henbucuoshanghai** [yuanyuanli85/tf-hrnet#6]
请问大佬那几个算法成熟呢？openpose，alphapose之外呢？

**Comment by yuanyuanli85** [comment]
你问的都是multiple person keypoint detection的网络，和这个repo没有直接关系吧。你能更详细一点吗？

**Comment by henbucuoshanghai** [comment]
多谢大佬热心。我在上海小公司，公司现在想做pose类项目，但不明确具体做什么，让我自己尝试。
我现在想的是先把主流的那几个算法demo跑出来，对比一下效果？然后看能做什么项目？ 这是开放的东西，大佬给点意见
同时，自己想去大厂，请问大佬怎样提高自己，怎样才算能力强呢？？

**Comment by yuanyuanli85** [comment]
先把主流的算法跑起来吧，自己感受一下精度和速度，看能否满足你们项目的要求。

**Comment by henbucuoshanghai** [comment]
目前没项目，    但是这能体现出我的 能力。。。  不懂
